// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"moocss.com/tiga/app"
	"moocss.com/tiga/internal/biz"
	"moocss.com/tiga/internal/data"
	"moocss.com/tiga/internal/service"
	"moocss.com/tiga/pkg/log"
)

// Injectors from wire.go:

func InitApp(logger log.Logger) (*app.App, error) {
	dataData, err := data.NewData(logger)
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo)
	userService := service.NewUserService(userUsecase, logger)
	postRepo := data.NewPostRepo(dataData, logger)
	postUsecase := biz.NewPostUsecase(postRepo)
	postService := service.NewPostService(postUsecase, logger)
	services := &service.Services{
		UserService: userService,
		PostService: postService,
	}
	appApp := newApp(logger, services)
	return appApp, nil
}
